services:
  - type: web
    name: cigkofte-backend
    runtime: docker
    plan: free
    envVars:
      - key: MYSQL_URI
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: SESSION_SECURE
        value: "true"
      - key: SESSION_SAMESITE
        value: None
